name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: get build time
        id: build-time
        run:  echo "buildtime=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Build JAR
        run: mvn package -DBUILD_TIMESTAMP=${{ steps.build-time.outputs.buildtime }}    # Use 'mvn' command instead of './mvnw'