name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'

      - name: Build JAR
        run: mvn clean package  # Use 'mvn' command instead of './mvnw'

      - name: Use Timestamp in Build
        run: |
          # Use the build timestamp from the pom.xml properties in your build/test commands
          echo "Using BUILD_TIMESTAMP: ${maven.build.timestamp}"
          echo "::set-output name=custom_timestamp::${maven.build.timestamp}"

      - name: Use Custom Timestamp in Build
        run: |
          # Use the custom timestamp in your build/test commands
          echo "Using CUSTOM_TIMESTAMP: ${{ steps.use-timestamp-in-build.outputs.custom_timestamp }}"